
const property = [{
  id: 1,
  owner: 1,
  status: 'available',
  price: 12000000,
  state: 'kano',
  city: 'kano',
  address: '15 Burma road',
  type: 'flat',
  created_on: Date(),
  image_url: 'image_url',
},
{
  id: 2,
  owner: 1,
  status: 'available',
  price: 12000000,
  state: 'abuja',
  city: 'kano',
  address: '15 Burma road',
  type: 'duplex',
  created_on: Date(),
  image_url: '',
},
{
  id: 3,
  owner: 1,
  status: 'available',
  price: 12000000,
  state: 'lagos',
  city: 'kano',
  address: '15 Burma road',
  type: 'terrace',
  created_on: Date(),
  image_url: '',
},
{
  id: 4,
  owner: 1,
  status: 'available',
  price: 400000,
  state: 'Abia',
  city: 'Aba',
  address: '15 WHA aba',
  type: 'flat',
  created_on: Date(),
  image_url: '',
},
{
  id: 5,
  owner: 3,
  status: 'available',
  price: 56000000,
  state: 'Imo',
  city: 'Owerri',
  address: '15 WHA Owerri',
  type: 'duplex',
  created_on: Date(),
  image_url: '',
},
{
  id: 6,
  owner: 1,
  status: 'available',
  price: 78000000,
  state: 'FCT',
  city: 'Abuja',
  address: 'Trademore estate Lugbe',
  type: 'terrace',
  created_on: Date(),
  image_url: '',
},
];

export default property;
